USE [GD1C2015]
DROP PROCEDURE [LA_MAQUINA_DE_HUMO].[Login]
DROP PROCEDURE [LA_MAQUINA_DE_HUMO].[obtenerRoles]
DROP PROCEDURE [LA_MAQUINA_DE_HUMO].obtenerFuncionalidadesDeRol
DROP PROCEDURE [LA_MAQUINA_DE_HUMO].SetFecha
DROP FUNCTION [LA_MAQUINA_DE_HUMO].obtenerFecha
DROP PROCEDURE [LA_MAQUINA_DE_HUMO].obtenerClienteDeUsuario
GO
DROP TABLE [LA_MAQUINA_DE_HUMO].[FECHA_DEL_SISTEMA]
GO
DROP TABLE [LA_MAQUINA_DE_HUMO].[Transaccion]
GO
DROP TABLE [LA_MAQUINA_DE_HUMO].[Factura]
GO
DROP TABLE [LA_MAQUINA_DE_HUMO].[Item]
GO
DROP TABLE [LA_MAQUINA_DE_HUMO].[Transferencia]
GO
DROP TABLE [LA_MAQUINA_DE_HUMO].[Cheque]
GO
DROP TABLE [LA_MAQUINA_DE_HUMO].[Banco]
GO
DROP TABLE [LA_MAQUINA_DE_HUMO].[Retiro]
GO
DROP TABLE [LA_MAQUINA_DE_HUMO].[Deposito]
GO
DROP TABLE [LA_MAQUINA_DE_HUMO].[Tarjeta]
GO
DROP TABLE [LA_MAQUINA_DE_HUMO].[Cuenta]
GO
DROP TABLE [LA_MAQUINA_DE_HUMO].[Clientes]
GO
DROP TABLE [LA_MAQUINA_DE_HUMO].[Tipo_Cuenta]
GO
DROP TABLE [LA_MAQUINA_DE_HUMO].[Moneda]
GO
DROP TABLE [LA_MAQUINA_DE_HUMO].[Pais]
GO
DROP TABLE [LA_MAQUINA_DE_HUMO].[Documento]
GO
DROP TABLE [LA_MAQUINA_DE_HUMO].[Auditoria]
GO
DROP TABLE [LA_MAQUINA_DE_HUMO].[Usuario]
GO
DROP TABLE [LA_MAQUINA_DE_HUMO].[Rol_Funcionalidad]
GO
DROP TABLE [LA_MAQUINA_DE_HUMO].[Funcionalidad]
GO
DROP TABLE [LA_MAQUINA_DE_HUMO].[Rol]
GO
DROP SCHEMA[LA_MAQUINA_DE_HUMO]

