USE [GD1C2015]
GO
DROP TABLE [LA_MAQUINA_DE_HUMO].[Clientes]
GO
DROP TABLE [LA_MAQUINA_DE_HUMO].[Pais]
GO
DROP TABLE [LA_MAQUINA_DE_HUMO].[Documento]
GO
DROP TABLE [LA_MAQUINA_DE_HUMO].[Auditoria]
GO
DROP TABLE [LA_MAQUINA_DE_HUMO].[Usuario]
GO
DROP TABLE [LA_MAQUINA_DE_HUMO].[Rol_Funcionalidad]
GO
DROP TABLE [LA_MAQUINA_DE_HUMO].[Funcionalidad]
GO
DROP TABLE [LA_MAQUINA_DE_HUMO].[Rol]
GO
DROP SCHEMA[LA_MAQUINA_DE_HUMO]

